name: FMTSI
favicon: null
layout_spectrum: 0.27652
typography_spectrum: 0.7799
title: 'Welcome To FMT Systems of Texas, Inc.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b4a594'
    - '#493c45'
    - '#0c0b0c'
    - '#947c65'
    - '#ecebec'
  brandStrength: 0.75
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 1
purpose: []
