name: FMTSI
favicon: null
layout_spectrum: 0.49227
typography_spectrum: 0.88069
title: 'FMT Systems of Texas, Inc.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-64480494-5
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b4a594'
    - '#493c45'
    - '#0c0b0c'
    - '#947c65'
    - '#ecebec'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
