name: FMTSI
favicon: null
layout_spectrum: 0.33332
typography_spectrum: 0.45576
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f3e9e7'
    - '#293e3e'
    - '#ad0036'
    - '#607684'
  brandStrength: 0.8692072459962219
  lightness: 0.1279544502031058
  saturation: 0.1803633589297533
  rhythmicContrast: 0.7336216107942164
purpose: []
