name: FMTSI
favicon: null
layout_spectrum: 0.33332
typography_spectrum: 0.45576
title: 'Welcome To FMT Systems of Texas, Inc.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#9b9b9b'
    - '#d7d8d9'
    - '#3a3b3b'
  brandStrength: 1
  lightness: 0.125
  saturation: 0
  rhythmicContrast: 0.7336216107942164
purpose: []
